pipelines:
  default:
    - step:
        image: python:2.7
        script:
          - pip install -U .[tests]
          - pytest -sv --cov=wotpy
    - step:
        image: python:3.6
        script:
          - pip install -U .[tests]
          - pytest -sv --cov=wotpy
