pipelines:
  default:
    - step:
        image: python:2.7
        script:
          - pip install -U .[tests]
          - pytest -sv --cov=wotpy
    - step:
        image: python:3.6
        script:
          - pip install -U .[tests]
          - pytest -sv --cov=wotpy
        services:
          - mosquitto
        environment:
          WOTPY_TESTS_MQTT_BROKER_URL: mqtt://localhost
    - step:
        image: python:3.7
        script:
          - pip install -U .[tests]
          - pytest -sv --cov=wotpy
        services:
          - mosquitto
        environment:
          WOTPY_TESTS_MQTT_BROKER_URL: mqtt://localhost
definitions:
  services:
    mosquitto:
      image: agmangas/mosquitto-websockets